FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt /app/
COPY ./server/server_app.py /app/
COPY protofile_pb2_grpc.py /app/
COPY protofile_pb2.py /app/
COPY protofile_pb2.pyi /app/

RUN pip install -r requirements.txt --no-cache-dir
RUN ls -l

CMD [ "python3","./server_app.py" ]





