version: "3.8"
services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  cs:
    build: ./cs
    container_name: cs
    ports:
      - "8000:8000"
    environment:
      - PROM_URL=http://prometheus:9090
    depends_on:
      - prometheus
