apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
  namespace: rag
type: Opaque
stringData:
  GEMINI_API_KEY: "AIzaSyA62QnJ14Ngxy7YMTtYMgL1H0xDZPfVJ5U"
  GROQ_API_KEY: "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"
