apiVersion: apps/v1
kind: Deployment
metadata: 
  name: grpc-client-deployment  
  namespace: target-services
  labels:
    app: grpc-client

spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-client

  template:
    metadata:
      labels:
        app: grpc-client

    spec:
      containers:
        - name: test-client
          image: chandrashekar316/capstone:grpc_client
          imagePullPolicy: IfNotPresent

