# prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# --- CS (Container-Spine) PromQL Rules ---
rule_files:
  - 'cs_rules.yml'
  
# --- CR (Container-Red Blood Cells) Scrape Job ---
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    # Scrapes the CH (Container-Heart) host
    static_configs:
      - targets: ['node-exporter:9100']
      
  - job_name: 'cs_ml_service'
    # Scrapes the CS service for its own health/latency metrics (optional but good practice)
    # The 'metrics_path' is correct here, and is indented properly under 'job_name'.
    metrics_path: /metrics
    static_configs:
     - targets: ['cs-ml-service:8000'] # Assuming the ML service exposes health metrics on 8000


  - job_name: 'cs_predictions_metrics'
    metrics_path: /metrics 
    static_configs:
    #testing
      - targets: ['cs-ml-service:9001']