# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cb_model_v2_pb2 as cb__model__v2__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cb_model_v2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CBModelServiceStub(object):
    """=============================================================================
    CB (Container-Brain) LLM Service - V2 with Rich Alert Context
    =============================================================================
    This service provides gRPC interface for LLM completions with structured
    Kubernetes/Istio context for intelligent alert analysis and remediation.
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeAlert = channel.unary_unary(
                '/cb_model.CBModelService/AnalyzeAlert',
                request_serializer=cb__model__v2__pb2.AlertAnalysisRequest.SerializeToString,
                response_deserializer=cb__model__v2__pb2.AlertAnalysisResponse.FromString,
                _registered_method=True)
        self.GenerateCompletion = channel.unary_unary(
                '/cb_model.CBModelService/GenerateCompletion',
                request_serializer=cb__model__v2__pb2.CompletionRequest.SerializeToString,
                response_deserializer=cb__model__v2__pb2.CompletionResponse.FromString,
                _registered_method=True)
        self.StreamCompletion = channel.unary_stream(
                '/cb_model.CBModelService/StreamCompletion',
                request_serializer=cb__model__v2__pb2.CompletionRequest.SerializeToString,
                response_deserializer=cb__model__v2__pb2.CompletionChunk.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/cb_model.CBModelService/HealthCheck',
                request_serializer=cb__model__v2__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=cb__model__v2__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/cb_model.CBModelService/GetModelInfo',
                request_serializer=cb__model__v2__pb2.ModelInfoRequest.SerializeToString,
                response_deserializer=cb__model__v2__pb2.ModelInfoResponse.FromString,
                _registered_method=True)


class CBModelServiceServicer(object):
    """=============================================================================
    CB (Container-Brain) LLM Service - V2 with Rich Alert Context
    =============================================================================
    This service provides gRPC interface for LLM completions with structured
    Kubernetes/Istio context for intelligent alert analysis and remediation.
    =============================================================================

    """

    def AnalyzeAlert(self, request, context):
        """Generate a completion from the LLM with full context
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateCompletion(self, request, context):
        """Simple completion (backward compatible)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCompletion(self, request, context):
        """Stream completion tokens as they're generated
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Check if the model is ready to serve requests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Get information about the loaded model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CBModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeAlert,
                    request_deserializer=cb__model__v2__pb2.AlertAnalysisRequest.FromString,
                    response_serializer=cb__model__v2__pb2.AlertAnalysisResponse.SerializeToString,
            ),
            'GenerateCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCompletion,
                    request_deserializer=cb__model__v2__pb2.CompletionRequest.FromString,
                    response_serializer=cb__model__v2__pb2.CompletionResponse.SerializeToString,
            ),
            'StreamCompletion': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCompletion,
                    request_deserializer=cb__model__v2__pb2.CompletionRequest.FromString,
                    response_serializer=cb__model__v2__pb2.CompletionChunk.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=cb__model__v2__pb2.HealthCheckRequest.FromString,
                    response_serializer=cb__model__v2__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=cb__model__v2__pb2.ModelInfoRequest.FromString,
                    response_serializer=cb__model__v2__pb2.ModelInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cb_model.CBModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cb_model.CBModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CBModelService(object):
    """=============================================================================
    CB (Container-Brain) LLM Service - V2 with Rich Alert Context
    =============================================================================
    This service provides gRPC interface for LLM completions with structured
    Kubernetes/Istio context for intelligent alert analysis and remediation.
    =============================================================================

    """

    @staticmethod
    def AnalyzeAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cb_model.CBModelService/AnalyzeAlert',
            cb__model__v2__pb2.AlertAnalysisRequest.SerializeToString,
            cb__model__v2__pb2.AlertAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cb_model.CBModelService/GenerateCompletion',
            cb__model__v2__pb2.CompletionRequest.SerializeToString,
            cb__model__v2__pb2.CompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cb_model.CBModelService/StreamCompletion',
            cb__model__v2__pb2.CompletionRequest.SerializeToString,
            cb__model__v2__pb2.CompletionChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cb_model.CBModelService/HealthCheck',
            cb__model__v2__pb2.HealthCheckRequest.SerializeToString,
            cb__model__v2__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cb_model.CBModelService/GetModelInfo',
            cb__model__v2__pb2.ModelInfoRequest.SerializeToString,
            cb__model__v2__pb2.ModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
