# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import alert_pb2 as alert__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in alert_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlertRemediationServiceStub(object):
    """=============================================================================
    Alert Remediation Service
    =============================================================================
    Server: Receives alerts from AlertManager, enriches context, sends to client
    Client: Receives enriched alerts, calls Gemini API with MCP for remediation
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeAndRemediate = channel.unary_unary(
                '/alert_remediation.AlertRemediationService/AnalyzeAndRemediate',
                request_serializer=alert__pb2.AlertRequest.SerializeToString,
                response_deserializer=alert__pb2.AlertResponse.FromString,
                _registered_method=True)
        self.AnalyzeAndRemediateStream = channel.unary_stream(
                '/alert_remediation.AlertRemediationService/AnalyzeAndRemediateStream',
                request_serializer=alert__pb2.AlertRequest.SerializeToString,
                response_deserializer=alert__pb2.RemediationUpdate.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/alert_remediation.AlertRemediationService/HealthCheck',
                request_serializer=alert__pb2.HealthRequest.SerializeToString,
                response_deserializer=alert__pb2.HealthResponse.FromString,
                _registered_method=True)


class AlertRemediationServiceServicer(object):
    """=============================================================================
    Alert Remediation Service
    =============================================================================
    Server: Receives alerts from AlertManager, enriches context, sends to client
    Client: Receives enriched alerts, calls Gemini API with MCP for remediation
    =============================================================================

    """

    def AnalyzeAndRemediate(self, request, context):
        """Send enriched alert from server to client for analysis and remediation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeAndRemediateStream(self, request, context):
        """Stream remediation progress updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlertRemediationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeAndRemediate': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeAndRemediate,
                    request_deserializer=alert__pb2.AlertRequest.FromString,
                    response_serializer=alert__pb2.AlertResponse.SerializeToString,
            ),
            'AnalyzeAndRemediateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.AnalyzeAndRemediateStream,
                    request_deserializer=alert__pb2.AlertRequest.FromString,
                    response_serializer=alert__pb2.RemediationUpdate.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=alert__pb2.HealthRequest.FromString,
                    response_serializer=alert__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alert_remediation.AlertRemediationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('alert_remediation.AlertRemediationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlertRemediationService(object):
    """=============================================================================
    Alert Remediation Service
    =============================================================================
    Server: Receives alerts from AlertManager, enriches context, sends to client
    Client: Receives enriched alerts, calls Gemini API with MCP for remediation
    =============================================================================

    """

    @staticmethod
    def AnalyzeAndRemediate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alert_remediation.AlertRemediationService/AnalyzeAndRemediate',
            alert__pb2.AlertRequest.SerializeToString,
            alert__pb2.AlertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeAndRemediateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/alert_remediation.AlertRemediationService/AnalyzeAndRemediateStream',
            alert__pb2.AlertRequest.SerializeToString,
            alert__pb2.RemediationUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alert_remediation.AlertRemediationService/HealthCheck',
            alert__pb2.HealthRequest.SerializeToString,
            alert__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
